"use client";
import { useRouter } from "next/navigation";
import { FormEvent, useState } from "react";

export function ContactForm({compact=false}:{compact?:boolean}){
 const router=useRouter(); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError("");const fd=new FormData(e.currentTarget);const payload=Object.fromEntries(fd.entries());
  try{const res=await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(!res.ok)throw new Error();router.push("/thank-you")}catch{setError("We could not submit your request. Please check the fields or contact us on WhatsApp.");setBusy(false)}}
 return <form className="neo-form" onSubmit={submit}><div className="field-row"><label>Full name<input name="name" required placeholder="Your name"/></label><label>Phone / WhatsApp<input name="phone" required inputMode="tel" placeholder="+92 3XX XXXXXXX"/></label></div><div className="field-row"><label>Email<input name="email" type="email" placeholder="you@example.com"/></label><label>Project location<input name="location" required placeholder="Islamabad, DHA, Bahria…"/></label></div><div className="field-row"><label>Service required<select name="service" required defaultValue=""><option value="" disabled>Select a service</option><option>Architectural Design</option><option>Residential Construction</option><option>Commercial Construction</option><option>Grey Structure</option><option>Turnkey Construction</option><option>Interior Design</option><option>Renovation</option><option>Project Management</option><option>Other</option></select></label><label>Plot / covered area<input name="area" placeholder="e.g. 10 marla"/></label></div>{!compact&&<label>Tell us about your project<textarea name="message" required rows={5} placeholder="Project type, current stage, requirements and expected start…"/></label>}<label className="consent"><input type="checkbox" required/> I consent to Neo using these details to respond to my enquiry.</label><input className="honey" name="website" tabIndex={-1} autoComplete="off"/><button className="button button-dark" disabled={busy}>{busy?"Sending…":"Send enquiry"}</button>{error&&<p className="form-error" role="alert">{error}</p>}</form>
}

export function QuoteForm(){
 const [step,setStep]=useState(1);const router=useRouter();const total=4;
 function next(e:FormEvent){e.preventDefault();setStep(s=>Math.min(total,s+1))}
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);await fetch("/api/contact",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(fd.entries()))});router.push("/thank-you")}
 return <div className="quote-wrap"><div className="quote-progress"><span style={{width:`${step/total*100}%`}}/><p>Step {step} of {total}</p></div><form className="neo-form quote-form" onSubmit={step===total?submit:next}>
  {step===1&&<><p className="eyebrow">01 · Your details</p><h2>How should we reach you?</h2><div className="field-row"><label>Full name<input name="name" required/></label><label>Phone / WhatsApp<input name="phone" required/></label></div><div className="field-row"><label>Email<input name="email" type="email"/></label><label>Preferred contact<select name="contact"><option>WhatsApp</option><option>Phone</option><option>Email</option></select></label></div></>}
  {step===2&&<><p className="eyebrow">02 · Project</p><h2>Tell us what you’re planning.</h2><div className="field-row"><label>Project type<select name="type"><option>New home</option><option>Commercial</option><option>Renovation</option><option>Interior</option></select></label><label>Service required<select name="service"><option>Architectural Design</option><option>Grey Structure</option><option>Turnkey Construction</option><option>Interior Design</option></select></label></div><div className="field-row"><label>Location<input name="location" required/></label><label>Plot / covered area<input name="area"/></label></div></>}
  {step===3&&<><p className="eyebrow">03 · Scope</p><h2>Help us understand the scope.</h2><div className="field-row"><label>Current stage<select name="stage"><option>Exploring options</option><option>Plot acquired</option><option>Design in progress</option><option>Drawings ready</option><option>Construction started</option></select></label><label>Desired start<input name="start" type="date"/></label></div><label>Key requirements<textarea name="requirements" rows={5} placeholder="Floors, basement, rooms, preferred style, interior needs…"/></label></>}
  {step===4&&<><p className="eyebrow">04 · Final details</p><h2>Anything else we should know?</h2><div className="field-row"><label>Estimated budget<select name="budget"><option>To be discussed</option><option>[Editable budget range 1]</option><option>[Editable budget range 2]</option></select></label><label>Reference document<input type="file" name="file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"/></label></div><label>Additional message<textarea name="message" rows={5}/></label><label className="consent"><input type="checkbox" required/> I consent to being contacted about this enquiry.</label><p className="form-note">Final pricing requires review of the site, drawings, specifications and project scope.</p></>}
  <div className="form-actions">{step>1&&<button type="button" className="text-button" onClick={()=>setStep(s=>s-1)}>← Back</button>}<button className="button button-dark">{step===total?"Submit requirements":"Continue →"}</button></div>
 </form></div>
}
